# Generated by Django 5.2 on 2025-05-06 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('peso', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unidade_medida', models.CharField(choices=[('g', 'Grama (g)'), ('ml', 'Mililitro (ml)'), ('un', 'Unidade (un)')], max_length=2)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='restaurantes.restaurante')),
            ],
        ),
    ]
