# Generated by Django 5.2 on 2025-05-06 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0002_insumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tempo_preparo', models.PositiveIntegerField(help_text='Tempo de preparo em minutos')),
                ('porcao_sugerida', models.CharField(max_length=100)),
                ('modo_preparo', models.TextField()),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='restaurantes.restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='ReceitaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_utilizada', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ic', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Índice de Cocção (IC)')),
                ('ipc', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Índice de Partes Comestíveis (IPC)')),
                ('aplicar_ic_ipc', models.BooleanField(default=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantes.insumo')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='restaurantes.receita')),
            ],
        ),
    ]
