# Generated by Django 5.2 on 2025-05-07 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0003_receita_receitainsumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('rendimento', models.CharField(max_length=100)),
                ('modo_preparo', models.TextField()),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_tecnicas', to='restaurantes.restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='FichaTecnicaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_utilizada', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unidade_medida', models.CharField(choices=[('g', 'g'), ('ml', 'ml'), ('un', 'un')], default='g', max_length=2)),
                ('ic', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Índice de Cocção (IC)')),
                ('ic_tipo', models.CharField(choices=[('menos', 'Menos (perda de peso)'), ('mais', 'Mais (ganho de peso)')], default='menos', max_length=10)),
                ('ipc', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Índice de Partes Comestíveis (IPC)')),
                ('aplicar_ic_ipc', models.BooleanField(default=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='restaurantes.fichatecnica')),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantes.insumo')),
                ('receita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantes.receita')),
            ],
        ),
    ]
