# Generated by Django 5.0.2 on 2025-05-08 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0004_fichatecnica_fichatecnicaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitainsumo',
            name='receita_sub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usos_como_subreceita', to='restaurantes.receita'),
        ),
        migrations.AlterField(
            model_name='receitainsumo',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantes.insumo'),
        ),
    ]
