# Generated by Django 5.2 on 2025-05-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0005_receitainsumo_receita_sub_alter_receitainsumo_insumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='custo_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='peso_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='receita',
            name='rendimento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
