# Generated by Django 5.2 on 2025-05-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0006_receita_custo_total_receita_peso_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatecnica',
            name='custo_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='peso_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
