# Generated by Django 5.2 on 2025-06-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0010_receita_valor_ifood_receita_valor_restaurante'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichatecnica',
            name='valor_ifood',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fichatecnica',
            name='valor_restaurante',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
