# Generated by Django 5.2 on 2025-06-26 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0012_registroatividade'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='fator_correcao',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
