# Generated by Django 5.2.3 on 2025-06-28 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0014_categoriainsumo_insumo_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPrecoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_precos', to='restaurantes.insumo')),
            ],
        ),
    ]
